apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      volumes:
        - name: data-input
          emptyDir: {}
        - name: data-output
          emptyDir: {}
      initContainers:
        - name: init
          image: busybox
          command:
            - /bin/sh
            - -c
            - echo "Initializing data" > /data/input/init.txt
          volumeMounts:
            - name: data-input
              mountPath: /data/input
      containers:
        - name: processor
          image: ghcr.io/den-vasyliev/go-demo-app:latest
          command: ["/bin/sh", "-c", "ls -l /data/input"]
          volumeMounts:
            - name: data-input
              mountPath: /data/input
            - name: data-output
              mountPath: /data/output
      restartPolicy: Never
  backoffLimit: 0
