apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
  labels:
    app: demo
spec:
  containers:
    - name: mycontainer
      image: ghcr.io/den-vasyliev/go-demo-app:latest
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never
