apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprobe
  labels:
    app: demo
spec:
  containers:
    - image: ghcr.io/den-vasyliev/go-demo-app:latest
      name: app
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
