---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
    - image: ghcr.io/den-vasyliev/go-demo-app:latest
      name: app
      ports:
        - containerPort: 8080
          name: http
